version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12

    environment:
      CI: true
      NODE_ENV: test

    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-dependencies-{{ .Branch }}-
            - v2-dependencies-

      - run: yarn install
      - run: yarn build
      - run: yarn test

      - save_cache:
          key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
